Configuring the role
Vettabase/ansible-mariadb-role-collection pull request #1
Opened 2022-05-11 01:50 UTC by aldoribeirojr

Creating the role chrony

2022-05-14 10:53 UTC, federico-razzoli requested changes

2022-05-14 10:53 UTC, federico-razzoli commented on chrony/files/chrony.conf
> +# one second, but only in the first three clock updates.
Add 1 newline at the end of every file

2022-05-14 10:53 UTC, federico-razzoli commented on chrony/handlers/main.yml
> +- name: restart chrony
First character uppercase: Restart chrony

2022-05-14 10:53 UTC, federico-razzoli commented on chrony/tests/test.yml
> +  remote_user: vagrant
I recommend to put all information needed for SSH connections into the inventory, including `remote_user`.

2022-05-14 10:53 UTC, federico-razzoli commented on chrony/tasks/main.yml
> +      - install_chrony
Note that you are not uploading the configuration file. Add a task for that.
Set the same owner, group and chmod as the original file.

2022-05-14 10:53 UTC, federico-razzoli commented on chrony/files/chrony.conf
> +# Welcome to the chrony configuration file. See chrony.conf(5) for more
Just to be sure: have you test the role? I'm asking because I didn't test it yet.
If it works, you did great! It's your first role, and I think you used handlers and tests correctly.

2022-05-16 02:00 UTC, federico-razzoli commented
You made one more commit but out of this pull request. Now it's hard for me to see which changes have been addressed.

I suggest you "move" the commit to this branch in this way:
* "import" the changes from `main` to this branch with `git merge`
* undo the last commit from main with `git reverse`
* run `git push --force`

2022-05-16 22:32 UTC, federico-razzoli commented
I'm very happy about this. It's simple, but it's a good role.

Just solve my final comments.
Also, at list one file is empty: `vars/main.yml`. Please delete empty files with `git rm` so the role is easier to look at.

2022-05-17 09:12 UTC, federico-razzoli requested changes

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/defaults/main.yml
> +public_ntp_servers:
Very good

2022-05-17 09:12 UTC, federico-razzoli commented on README.md
> +### Database:
Delete the ":" at the end of headers

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/tasks/main.yml
> +  notify: Restart chrony
Add 1 newline at the end of files

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/tasks/main.yml
> +- name: Deploy chrony.conf template
Very good

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/tasks/main.yml
> +- name: Deploy chrony.conf template
However, "deploy" is a generic word. Use "upload"

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/templates/chrony.conf.j2
> +{% for server in public_ntp_servers %}
Very good

2022-05-17 09:12 UTC, federico-razzoli commented on roles/chrony/templates/chrony.conf.j2
> +logdir /var/log/chrony
Newline

2022-05-17 09:12 UTC, federico-razzoli commented on chrony/.gitignore
> +.vscode
Newline

2022-05-19 13:06 UTC, aldoribeirojr reviewed
I fixed some issues

2022-05-19 17:45 UTC, aldoribeirojr commented
the questions were solved!

2022-05-19 17:49 UTC, federico-razzoli approved these changes

2022-05-19 17:49 UTC, federico-razzoli commented on chrony/files/chrony.conf
> +# one second, but only in the first three clock updates.
Should this file be deleted?

2022-05-19 17:51 UTC, federico-razzoli commented
I have to force the branch (`Merge without waiting for requirements to be met (administrators only)`) because Aldo's older commits were not signed. From now on all commits should be signed, and we won't force merges anymore.

2022-05-19 17:52 UTC, merged